# Generated by Django 3.0.5 on 2020-05-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pillbox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAndPillbox',
            fields=[
                ('user_name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('pillbox_id', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='theagedandmedicament',
            name='pill_time',
            field=models.DateTimeField(auto_now=True, verbose_name='TimeToHavePills'),
        ),
        migrations.AddField(
            model_name='userandtheaged',
            name='emergency_contact_1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userandtheaged',
            name='emergency_contact_2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userandtheaged',
            name='emergency_contact_3',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='theagedandmedicament',
            name='dosage',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='theagedandmedicament',
            name='freq',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='theagedandmedicament',
            name='unit',
            field=models.CharField(max_length=50),
        ),
    ]
